import type { PendingContentUpdate } from "@/lib/supabase/types";

export async function sendChangeNotificationEmail(params: {
  update: PendingContentUpdate;
  adminDashboardUrl: string;
}): Promise<boolean> {
  const { update, adminDashboardUrl } = params;
  const apiKey = process.env.RESEND_API_KEY;
  const adminEmail = process.env.ADMIN_EMAIL;
  const fromEmail =
    process.env.RESEND_FROM_EMAIL ?? "RelocateEU <onboarding@resend.dev>";

  if (!apiKey || !adminEmail) {
    console.warn(
      "RESEND_API_KEY or ADMIN_EMAIL not set — skipping email notification"
    );
    console.info("Pending update created:", update.id, update.label);
    return false;
  }

  const approveUrl = `${adminDashboardUrl}/admin?review=${update.id}`;

  const html = `
    <h2>RelocateEU — Official source content changed</h2>
    <p><strong>Source:</strong> ${update.label} (${update.domain})</p>
    <p><strong>Country:</strong> ${update.country}</p>
    <p><strong>URL:</strong> <a href="${update.source_url}">${update.source_url}</a></p>
    <p><strong>Summary:</strong> ${update.diff_summary ?? "Content changed"}</p>
    <hr />
    <h3>Previous snapshot</h3>
    <pre style="white-space:pre-wrap;background:#f4f4f5;padding:12px;border-radius:8px;font-size:12px;">${escapeHtml(update.old_content.slice(0, 2000))}</pre>
    <h3>New snapshot</h3>
    <pre style="white-space:pre-wrap;background:#eff6ff;padding:12px;border-radius:8px;font-size:12px;">${escapeHtml(update.new_content.slice(0, 2000))}</pre>
    <hr />
    <p><a href="${approveUrl}" style="display:inline-block;background:#2563eb;color:#fff;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600;">Review &amp; approve in dashboard</a></p>
    <p style="color:#64748b;font-size:12px;">This alert was generated by the weekly RelocateEU content monitor.</p>
  `;

  const response = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      from: fromEmail,
      to: [adminEmail],
      subject: `[RelocateEU] Content changed: ${update.label}`,
      html,
    }),
  });

  if (!response.ok) {
    console.error("Resend error:", await response.text());
    return false;
  }

  return true;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
